name: Daily ğŸª training and feeding

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  feed-and-train:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout ğŸª
        uses: actions/checkout@v2

      - name: Feed and train ğŸª
        uses: ./action.yml
        with:
          tc_user: ${{ secrets.TC_USER }}
          tc_password: ${{ secrets.TC_PASSWORD }}
