name: feed & train camel

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  feed-and-train:
    runs-on: ubuntu-latest
    steps:

      - name: Feed and train ğŸª
        uses: danthelion/tc-feeder@0.5
        env:
          TC_USER: ${{ secrets.TC_USER }}
          TC_PASSWORD: ${{ secrets.TC_PASSWORD }}
